"""Controlled axial stations for the bounded DF8 forward-arm repack."""

BASELINE_PIVOT_Z_MM = 900.0
ARM_PIVOT_Z_MM = 480.0
FORWARD_TRANSLATION_MM = BASELINE_PIVOT_Z_MM - ARM_PIVOT_Z_MM

FWD_RING_01_Z_MM = 340.0
FWD_RING_02_Z_MM = ARM_PIVOT_Z_MM - 15.0
ARM_STRUCTURE_START_Z_MM = ARM_PIVOT_Z_MM - 11.0
ARM_TERMINATION_RING_Z_MM = ARM_STRUCTURE_START_Z_MM + 749.0
AFT_ROUTE_RING_Z_MM = 1638.0

BOOSTER_BODY_START_Z_MM = 950.0
BOOSTER_INSTALL_RADIUS_MM = 15.5
BOOSTER_MANIFOLD_CLOCKS_DEG = (30.0, 150.0, 270.0)
BOOSTER_INSTALL_CLOCKS_DEG = (52.0, 172.0, 292.0)
BOOSTER_COLLECTION_CORRIDOR_RADIUS_MM = 18.0
BOOSTER_BAND_SCREW_LOCAL_X_MM = 7.5
WATER_TRIGGER_Z_MM = 1420.0
FULLFLOW_VALVE_Z_MM = ARM_TERMINATION_RING_Z_MM - 26.0

NOSE_TIP_TO_PIVOT_BASELINE_MM = BASELINE_PIVOT_Z_MM
NOSE_TIP_TO_PIVOT_NEW_MM = ARM_PIVOT_Z_MM
FWD_RING_01_TO_PIVOT_MM = ARM_PIVOT_Z_MM - FWD_RING_01_Z_MM
